#ifndef LEARNSHAREDLIB_GLOBAL_H
#define LEARNSHAREDLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LEARNSHAREDLIB_LIBRARY)
#  define LEARNSHAREDLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LEARNSHAREDLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LEARNSHAREDLIB_GLOBAL_H
